### ISSUE TITLE
Active WebMo Page (UI only)

### ISSUE THREAD

**Issue by ionutanin** [interledger/web-monetization-extension#101]
### Context

Implement active Web Monetization Page.

### Todos

- For a user that does have a connected wallet address, the web monetization page should be displayed
- Add setup form:
  - global enable/disable wm
  - current rate of pay slider
  - show the remaning balance
  - show the continuous toggle
  - enter amount to send now (tip)
- Validate form fields on submission
- The actions the user can perform are:
  - enable/disable wm
  - move rate of pay slider
  - enable/disable continous payments
  - send money now (tip)

**UI design:**
![Image](https://github.com/interledger/web-monetization-extension/assets/90185897/88da0c94-422c-4a40-9d5f-2a91aafe54d1)

**Comment by tselit** [comment]
Update: starting this has been delayed by PR reviews & feedback. Aiming to pick this up on Fri, 23 Feb.
