### ISSUE TITLE
Settings page - Disconnect wallet

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#108]
### Context
Implement the settings page to disconnect a wallet.
A WM extension user who has previously connected their digital wallet to fund their WM payments needs to be able to **disconnect** their digital wallet from the WM extension.

The settings page UI:
<img width="174" alt="disconnect wallet" src="https://github.com/interledger/web-monetization-extension/assets/90185897/a0820768-fe90-47de-b459-1c5b092ad784">

### Todos
- For a user that already has a connected wallet address, the settings page should display the following form fields:
  - the public key that was generated by the extension during installation (read-only with ability to copy the key value)
  - the full address of the connected wallet (should be disabled and read-only)
  - the remaining balance of the wallet (should be disabled and read-only)
  - the disconnect button
- Expire all grants / access tokens that had been issued to the extension for that wallet address.
 
- For a user that has disconnected a wallet address, all the setup form fields should be enabled and allow text entry. The actions that the user can perform are to:
  - view & copy the public key
  - enter the wallet address
  - enter the amount
  - select amount type (recurring/single use)
  - connecting a wallet address

**Comment by raducristianpopa** [comment]
Working, but not clearing the storage properly.

**Comment by tselit** [comment]
Addressing clearing storage after wallet disconnect in #174 - waiting for review

**Comment by raducristianpopa** [comment]
Closed by #174.
