### ISSUE TITLE
[Monetization flow - Background] Start payment

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#165]
4. In background - call `monetizationServer.start()`
   4.1 request incoming payment grant
   4.2 create incoming payment - NO AMOUNT
   4.3 try to send payment - if received status code is 403, rotate token
   4.4 revoke grant after creating incoming payment
   4.5 add incoming payment details to a map - (key: tabId, value: {"uuidv4" : { ...incomingPaymentDetails, active: true }, ...})
5. Create quote with `receiveAmount = RATE_OF_PAY / 3600` to incoming payment (active: true)
   5.1. We multiply by X times the interval (X - the number of link tags that we have in the page)
   5.2. What should happen when the wallet address has a low asset scale (2 for example)?
   - If the sending wallet address has a low asset scale how are we splitting the amounts? For asset scale 2 it will need to send 4 units ($0.04) - $0.02 for each link tag
   - If the receiving wallet address has a low asset scale - we will need to ignore the WM user rate of pay and send the minimum amount x number links (two links, with the minimum amount of 2 units - $0.04)
6. Create outgoing payment with quote identifier (active: true)

**Comment by ionutanin** [comment]
Covered:
- request incoming payment grant
- create incoming payment - NO AMOUNT
- try to send payment - if received status code is 403, rotate token
- revoke grant after creating incoming payment
- Create outgoing payment with quote identifier (active: true)

In progress:
- add incoming payment details to a map - (key: tabId, value: {"uuidv4" : { ...incomingPaymentDetails, active: true }, ...})
- We multiply by X times the interval (X - the number of link tags that we have in the page)
- If the sending wallet address has a low asset scale how are we splitting the amounts? For asset scale 2 it will need to send 4 units ($0.04) - $0.02 for each link tag
- If the receiving wallet address has a low asset scale - we will need to ignore the WM user rate of pay and send the minimum amount x number links (two links, with the minimum amount of 2 units - $0.04)

**Comment by tselit** [comment]
Still need to confirm the following point, but working towards completing and having PR ready for review tomorrow/Friday, 28/29 Mar
- add incoming payment details to a map

Functional testing (currently manual):
- test with 2 wallet addresses that have different asset scales

**Comment by tselit** [comment]
Overall, the task has been delayed due to (1) annual leave and (2) more complexity than anticipated. 
Peer reviews should be begin on Monday, 1 April
