### ISSUE TITLE
Move to MV3 as MV2 is going to be deprecated

### ISSUE THREAD

**Issue by ionutanin** [interledger/web-monetization-extension#23]
CORS on MV3
Use MonetizationEvent class rather than using custom events
Add script injection into content script on MV3 with monetization event (if necessary add script CSP sha)

- The component that searches for WM tags and event routing to WM tags should not run in the main JS context

**References on Chrome extension MV2 sunset timeline**: 
- https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline
- https://developer.chrome.com/blog/resuming-the-transition-to-mv3

**Comment by tselit** [comment]
Prioritising compatibility for Chrome first.
Agreed to work on compatibility for other engines after work-week.

**Comment by tselit** [comment]
Diana will investigate the approach that we'll need to ensure that the extension's polyfill capability is secure once we are MV3 compatible

There seems to be an issue with Firefox browser compatibility that will be an impediment for the MV3 update for the Firefox build.

**Comment by sidvishnoi** [comment]
Also relevant bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1573659
Firefox MV3 doesn't support service worker as of now. We'll need separate implementation wrappers as background script/service worker.

**Comment by tselit** [comment]
> Another difference we need to handle: By default, MV3 disables our all hosts permissions. That's something we need to request user, otherwise much of the extension won't work - can only open the popup, no payments or anything. Unfortunately, can't ask that permission on install either - needs user interaction. So, I'll see if we do something in UI (popup), or do it before we even show allow opening popup (less UI work that way).

Interesting, thanks Sid. I'd love to see a demo of the alternatives, actually.

**Comment by sidvishnoi** [comment]
Also, not a blocker, but Firefox doesn't support content script execution world yet as mentioned in https://github.com/interledger/web-monetization-extension/issues/9.
https://bugzilla.mozilla.org/show_bug.cgi?id=1736575
So, we'll have to stick with the inject `script.innerHTML` hack for now.

**Comment by sidvishnoi** [comment]
Ok, found the best bug yet. Thanks to webpack (or our configuration). It adds a `document` check to `background.js`, but Chrome MV3 (with Service Worker) doesn't support document, so I kept getting `document is not defined` errors from somewhere. 

Stack trace pointed only to our logger, so had to grep for document in bundles. Will check how do we avoid webpack adding that.

Rest of the extension seems to be working fine with Firefox/Chrome MV3 🎉

**Comment by sidvishnoi** [comment]
Question: @tselit @ioana-chiorean  @raducristianpopa @dianafulga 
Should we remove manifest v2 support, or continue to support it?
I found extension worked fine with Firefox MV3.

**Comment by tselit** [comment]
> Question: @tselit @ioana-chiorean @raducristianpopa @dianafulga Should we remove manifest v2 support, or continue to support it? I found extension worked fine with Firefox MV3.

Thanks Sid...it's interesting to hear that the extension using MV3 worked fine on Firefox (which version)?

I think you might've referenced this earlier, so I'm keen to understand how you got around this: "Chrome’s version of MV3 requires service worker-based background scripts, which Firefox does not support yet."

**Comment by sidvishnoi** [comment]
Please check linked PR, I added a review comment there about this.

**Comment by sidvishnoi** [comment]
Working fine on Firefox 110, including tipping and continuous payments.
![image](https://github.com/interledger/web-monetization-extension/assets/8426945/8289c7c5-158d-4413-b8f2-6d6d0f05b662)

(Firefox started MV3 support with 109, but I tested on 110)

**Comment by tselit** [comment]
Ready to merge.
Further discussion/consideration about the UI design/composition to address the issue with the scroll bar.
The other consideration (also a separate ticket) would be possibly overhauling the entire UI of the extension, possibly giving the user more direction on what to do next.
