### ISSUE TITLE
WM Extension to be available from the Chrome Web Store

### ISSUE THREAD

**Issue by ionutanin** [interledger/web-monetization-extension#24]

**Comment by sidvishnoi** [comment]
We'd eventually want to automate (whatever possible parts of) the publishing.
https://jam.dev/blog/automating-chrome-extension-publishing/
https://github.com/fregante/chrome-webstore-upload-cli

**Comment by RabebOthmani** [comment]
As a user, I want the WM extension to be available on the Chrome Web Store
So I can easily install it and use it. 

**Acceptance Criteria**

- This release will be published on the CWS as BETA with visibility set to unlisted. 
- Only users with direct link to the store listing will be able to install it. 
[Documentation on how to publish to CWS.](https://developer.chrome.com/docs/extensions/develop/migrate/publish-mv3#:~:text=First%2C%20you%20must%20label%20the,BETA%20TESTING%22%20to%20the%20description)

**Comment by RabebOthmani** [comment]
Extension is now available on the store.
