### ISSUE TITLE
Show remaining balance of authorized amnt

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#272]
When the WM extension is connected to a digital wallet, there is an amount of money/value that the user authorizes the extension to access from the user's connected wallet. 

The extension pop-up should accurately update the displayed remaining balance of the authorized total value.

- [x] https://github.com/interledger/web-monetization-extension/issues/376
- [ ] https://github.com/interledger/web-monetization-extension/issues/378
- [ ] https://github.com/interledger/web-monetization-extension/pull/386

**Comment by sidvishnoi** [comment]
Relevant: https://github.com/interledger/open-payments/issues/469

**Comment by RabebOthmani** [comment]
Is this ticket still blocked @raducristianpopa @sidvishnoi?

**Comment by sidvishnoi** [comment]
Correct. Still blocked.

**Comment by RabebOthmani** [comment]
What's blocking it? Tseli mentioned that the Open Payments issue is resolved. I guess we also need to define the UI

**Comment by sidvishnoi** [comment]
Pending on releases (Rafiki, Open Payments client).

UI: I think there's something in the Figma (link in `#web-monetization-extension` Slack channel's pinned message), but not sure if it's outdated

**Comment by sidvishnoi** [comment]
https://rafiki.money now returns `grantSpentDebitAmount`.
Now blocked only on open-payments SDK update.
