### ISSUE TITLE
[Background] Split sent amount

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#285]
Context:
In alpha when there are multiple monetization links in a page, we sent the rate of pay that the user sets up in the interface, to each link.

Desired behaviour:
The rate of pay that is setup by the user in the interface should be divided by number of monetized links in the page, sent that amount to each link.

Implementation details:
If there are iframes in the page this is going to be the behaviour:
- the main frame will send the links found in the page => the monetization will start on each link from the main frame with rateOfPay divided by number of links in the main frame
- the first iframe will send the links found in the iframe => the monetization will start on each link from the iframe with rateOfPay divided by the number of links in main frame + first iframe, the existing monetization links from the main frame will have the amount updated to this amount
- the second iframe will send the links found in the iframe => the monetization will start on each link from the iframe with rateOfPay divided by the number of links in main frame + first iframe + second iframe, the existing monetization links from the main frame + first iframe will have the amount updated to this amount
- and so on, for each iframe found in the page

There is a possibility for a few seconds, depending on how many links are in the page) to have different amounts send to links, until we parse all links.

**Comment by tselit** [comment]
Expecting to get into review tomorrow, 5 June.

**Comment by tselit** [comment]
**Note**: Tseli & Diana discussed, and will update the description to expand a little bit on how this ticket differs from the alpha 1 release.
