### ISSUE TITLE
[Background] Overpaying

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#286]
Ordering: this ticket should ideally follow #145 

If the receiver’s wallet cannot receive AMOUNT, we should send the minimum amount that can be sent. If the receiver’s asset scale is 2, we will not be able to send SPLITTED_AMOUNT, and we need to send the smallest unit 1 + 1 (we can not send 1 - cause: @interledger/pay library, used in Rafiki). We call this action OVERPAYING. We also need to adjust the payment interval. By default, the happy path, we send a payment every second. If overpaying, we need to adjust the interval as well: We need to send a payment every 30 seconds (dynamic - it will not always be 30 seconds, we need to calculate the interval based on the smallest amount that can be sent) to facilitate RATE_OF_PAY. 

- set the amount as minimum in the constructor or when recalculating the rate.
- if overpaying, calculate the interval as well:  0.02 * 3600/0.60 = 120s (2 minutes)

When a payment session is overpaying we need to store the last payment timestamp. Reasoning: if a user keeps refreshing a page and we have a payment session that is overpaying, we will send $0.02 whenever a payment session is established for the wallet address . If we have the timestamp, we can check if the page has received a payment before and if CURRENT_TIMSTAMP is not greater than the payment timestamp we will wait for CURRENT_TIMESTAMP - PAYMENT_TIMESTAMP until sending the next payment.

Whenever a payment session is overpaying save:
- Website url (we store the sha1 the URL)
- Tab ID
- Wallet address
- Last payment timestamp
- Expires At = Last payment timestamp + MS (TBD)

Whenever we receive the START_MONETIZATION event, we check the overpaying state for the current tab + website url. If a record is found, initialize a new payment session but do not start it. We need to wait for LAST_PAYMENT_TIMESTAMP + INTERVAL (dynamic for each payment session that is overpaying) - CURRENT_TIMESTAMP

**Comment by tselit** [comment]
The team revised the approach for this which impacts the estimated effort = adding another 32 days = 72 hrs (noting that Monday is a national holiday in Romania). Aiming to put into review by Thurs, 27 June.

**Comment by sidvishnoi** [comment]
We can't use `Tab` as the references aren't stable across calls. Need to fall back to `tabId` approach here, and add a cleanup process. See https://github.com/interledger/web-monetization-extension/pull/420#issuecomment-2225770302
