### ISSUE TITLE
[Background] Handle token rotation synchronously

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#288]
When there are multiple link tags on a page, each link tag may going to try to rotate its token

---

If there are multiple payment sessions for a tab and the token expires, each payment session will try to rotate the token and the monetization flow will break because of the race condition.

To be implemented:
- move token rotation logic in `OpenPaymentsService`
- dedupe token rotation calls and cache the results for a small amount of time

**Comment by tselit** [comment]
Investigating approaches and revising this in progress
