### ISSUE TITLE
Cross-currency monetization

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#291]
### Context

With the current implementation from #145, we didn't really test the monetization in a cross-currency scenario.
At the moment, when performing a cross-currency transaction we get the following result for an outgoing payment:
```json
{
    "id": "https://ilp.rafiki.money/outgoing-payments/191326a9-258e-42ec-88b1-a8944ece85de",
    "walletAddress": "https://ilp.rafiki.money/radu-ron",
    "quoteId": "https://ilp.rafiki.money/quotes/191326a9-258e-42ec-88b1-a8944ece85de",
    "receiveAmount": {
        "value": "1",
        "assetCode": "EUR",
        "assetScale": 2
    },
    "debitAmount": {
        "value": "2",
        "assetCode": "RON",
        "assetScale": 2
    },
    "sentAmount": {
        "value": "0",
        "assetCode": "RON",
        "assetScale": 2
    },
    "receiver": "https://ilp.rafiki.money/incoming-payments/702f3079-fc00-4222-aded-791aa39bbafd",
    "failed": false,
    "metadata": {
        "source": "Web Monetization"
    },
    "createdAt": "2024-05-28T06:01:23.315Z",
    "updatedAt": "2024-05-28T06:01:23.315Z"
}
```

When performing FX on the `debitAmount` (0.02 RON to EUR) it results: 0.0040EUR, but the `receiveAmount` is set to 1 unit of EUR (0.01EUR).

Slack thread [here](https://interledgerfoundation.slack.com/archives/C05EMHTG6FM/p1716803842183209).

_Details TBD_

### Todos

_TBD_

**Comment by raducristianpopa** [comment]
Related https://github.com/interledger/rafiki/issues/2770

**Comment by tselit** [comment]
To do: @raducristianpopa to link with a Rafiki PR
