### ISSUE TITLE
False-positive 1-time payment success msg

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#292]
### Steps to reproduce

**Wallet setup**
1. Successfully created a USD sender test wallet account in rafiki.money.
2. Successfully connected the wallet address to the extension.

**Visited websites**
1. Visited radu.sh and the WM icon was green
2. Successfully made a one-time payment to [radu.sh](radu.sh) (so far, so good :smiley: )

3. Visited [google.com](google.com) (a non-WMized website) and the WM icon remained red 
5. I opened the WM ext, entered an amount, and attempted to make a 1-time payment to google.com.
6. The ext said "This website is not monetized."   (still going well :smiley: )

7. While I still had google.com open, with the WM ext open, and a value on the page for sending a 1-time payment
8. I used a keyboard shortcut to open the browser dev tools (**note:** the Web browser window remained open on the side, with the extension pop-up also **still** open) and I clicked around in the dev tools window
9. I then moved the mouse back to the Web browser, and clicked "Send Money" on the extension
10. The extension showed the message "payment successful"   (this can't be 👎🏾 )

### Expected result

No payments can happen, and no payment success messages can be valid when attempting to pay a non-monetized website with the extension.

### Actual result

The extension indicated that a one-time payment to google.com had succeeded.

### Screenshots or videos

**Link to video**: [on loom](https://www.loom.com/share/07ca89dcfd094e89af40e3408be0ab13?sid=dfa6ab83-ccbb-47d6-be0b-c229a0c9183b)

Was able to replicate behaviour on dev.to:
![image](https://github.com/interledger/web-monetization-extension/assets/90185897/6b250f5e-ab30-4819-b21c-afb1f2c77851)

### Additional context
We also noticed that there are instances where a website has multiple valid wallet addresses, and a one-time payment only succeeds in that some of the wallet addresses receive payment, and others do not (for example, if the sending wallet exceeds the authorized amount after successfully making 1 of 2 payments).

_No response_

### Operating system

Windows

### Operating system version

10

### Browsers

Chrome

### Browser version

125.0.6422.78

### Extension version

alpha 1 (the ext shows v1.0.1)

**Comment by tselit** [comment]
**To do**: @tselit to log a separate ticket (using the same video attached to this ticket, re. concatenated text on the "Send now" button.

So this is ready for review.

**Comment by raducristianpopa** [comment]
Closed by #333.
