### ISSUE TITLE
Remove `prettier` ESLint plugin

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#30]
Prettier doesn't care if we've got unused vars lying around or if there's some weird scoping issue. This is where ESLint comes in handy. I reckon it's a good idea to keep our formatting and linting separate.

https://prettier.io/docs/en/comparison

CC @dianafulga @ionutanin

**Comment by ionutanin** [comment]
@raducristianpopa If I'm not mistaken, I think I've set it already to throw an error on unused vars on pre-commit. Isn't it? I'll check it out
