### ISSUE TITLE
[BUG] Unable to build project unless I downgrade node:fetch version 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#316]
### Steps to reproduce

I tried to build the project locally on my machine but kept getting an error message " Module build failed: UnhandledSchemeError: Reading from "node:fetch" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs." 

### Expected result

Following all the steps on the ReadMe and installing all necessary modules, I was expecting the project to build without having to fiddle with any versions. But since it seems like this is a known issue with node, maybe we should at least mention it on the ReadMe for users to know how to handle the issue.

### Actual result

The workaround to make the project build is to downgrade the node:fetch version. It does seem to be a known issue https://github.com/vercel/next.js/discussions/33982 . 

### Operating system

Windows

### Browsers

Chrome

### Extension version

Alpha

**Comment by dianafulga** [comment]
Findings on Windows: 
- node-fetch is not a direct dependency on the extension, but it is used under the hood by apidevtools (json-schema-ref-parser).
- `pnpm install `works, but `pnpm dev` it's the one throwing the error
- this code in the extension it's not enough:
```
new IgnorePlugin({
    resourceRegExp: /node-fetch/,
    contextRegExp: /@apidevtools\/json-schema-ref-parser/
  })
```
A quick fix, just have it temporary working would be to install node-fetch as direct dependency and set the version to 2.5.0.
A possible valid, permanent solution would be to fix the dependency in apidevtools

**Comment by RabebOthmani** [comment]
@dianafulga should we expand on this on the ReadMe as a known issue? Or hold off and see if we get any complaints ?

**Comment by dianafulga** [comment]
@RabebOthmani I would link this ticket to the one from the open payments, and set it in ReadMe as a known issue, until it's resolved on their side.
