### ISSUE TITLE
[FEATURE REQUEST] UX - enhance WM ext visual cues on non-monetized websites

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#318]
### Describe the feature you would like to request

As a user, when I'm on a non-monetized website
I want to have a clear visual indication that the website is not monetized
So I'm not wasting time and energy on the payment flow that will eventually fail 

### Describe the solution you would like

Currently if I go to rabebothmani.com which is not monetized, I'm able to see the extension and process a payment 

![WM extension enabled on bibi website ](https://github.com/interledger/web-monetization-extension/assets/5781590/e8e19ef7-c910-4402-945e-ddd42e0f5fb3)

It's not until I click on pay now that I get an error message telling me the website is not monetized 

![not monetized](https://github.com/interledger/web-monetization-extension/assets/5781590/e9b25a65-a36d-4a85-9e03-2b1e26e3761b)

This can create frustration with users. Instead, we can: 
option 1: completely disable the extension on non-monetized websites. The risk with this approach is it can create confusion for users wondering why their extension is not working
option2: A different UI for non-monetized websites with a simple message along the lines " We appreciate you wanting to support <url> , unfortunately web monetization was not enabled here"

**Comment by tselit** [comment]
Thanks for this @RabebOthmani!
Let us chat about this a little bit tomorrow.
This could definitely better support UX.

Just to add that the teeny-tiny red X on the extension is meant to indicate that this is a non-monetized website (also, I'm aware that accessibility may be an issue as red assumes colour interpretation, which actually may not be accessible for everyone).

**Comment by RabebOthmani** [comment]
@tselit we might have a little bug on our hands as I can see a green dot on my website not the red one 
![extension green](https://github.com/interledger/web-monetization-extension/assets/5781590/1f1cbc0b-72bc-4b48-aea8-1d3b52cab955)

**Comment by tselit** [comment]
Today we discussed that the message displayed on the pop-up should perhaps be softer (or more informational) rather than appearing as an error message. @tselit & @sidvishnoi will chat later today.

**Comment by tselit** [comment]
@RabebOthmani what do think about this?
![image](https://github.com/interledger/web-monetization-extension/assets/90185897/c0465731-5cb6-4e30-960f-2610717e4be4)

**Comment by RabebOthmani** [comment]
@tselit @sidvishnoi I'm aware we may not have much control over the size of the pop up. There's a lot of empty space there, do we want to try make the text bold in the centre of the pop up to ensure it catches the attention of the user? 
Please note we can go with the screen as it is if we have other items higher on priority :)

**Comment by tselit** [comment]
Thanks @RabebOthmani.
Cool, and here's the updated UI 👇🏾 . @sidvishnoi I think this is ready for you:
![image](https://github.com/interledger/web-monetization-extension/assets/90185897/077d5690-ad38-4c83-96b6-75330d51f3a6)

[Link to Figma](https://www.figma.com/design/0S8Oj8ZB5MvkGtIrVRswDH/Web-monetization?node-id=1272-840&t=WMFiEmxAD8dnaa60-4) design for v1.0
