### ISSUE TITLE
[BUG] Payment failing 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#320]
### Steps to reproduce

I'm testing out the extension. 
This is how my settings look like:

![wallet ](https://github.com/interledger/web-monetization-extension/assets/5781590/f4328c0f-e2a4-454e-a814-18aa56a7281e)

I tried to process a payment on https://alexlakatos.com/ then on https://www.radu.sh/ 

### Expected result

I would expect my payment to succeed or at least in case of failure, I'd expect to see a clear message with the reason behind the failure. 

### Actual result

On Alex's website, the first error message I received was website not monetized then after retrial I got  we can't facilitate the payment.
On Radu's website, I got we can't facilitate the payment. 

![WM Extension error message ](https://github.com/interledger/web-monetization-extension/assets/5781590/d1f2cc52-5baa-4913-a85d-de754ba58013)

![WM Extension correct error message ](https://github.com/interledger/web-monetization-extension/assets/5781590/23e5fdc3-4f90-4f19-9898-7261850cb54a)

![payment radu](https://github.com/interledger/web-monetization-extension/assets/5781590/da4e1005-ba74-42cd-8d46-4d7f4ade9979)

I'm not sure if I'm doing something wrong on my side. 

### Operating system

Windows

### Browsers

Chrome

### Extension version

Alpha

**Comment by sidvishnoi** [comment]
We pay from the initially granted balance only. In this case, grant was for 0.25 but payments are larger.

We can either:
- show better error message or disallow pay if balance is less than pay amount, or
- if balance is low (or always) pay from a using a new interactive grant for one time payment, instead of from existing grant.

In case of (1), it would be helpful to know the balance and show it to user.

**Comment by RabebOthmani** [comment]
My goal was to test and see what error messages we are providing users with thus the amount being larger. But even when I try to test with an amount that's available, the payment still fails. 
I'm wondering if there's a minimum amount. I purposely wanted to test with edge cases like tiny amounts etc

**Comment by RabebOthmani** [comment]
After further investigation, this issue is about: 
* Extension did not stop me from connecting to a non WM pointer. 
* Extension did not disconnect once the key has been dissociated from account

**Comment by RabebOthmani** [comment]
Breaking this issue to smaller ones and closing this. 
https://github.com/interledger/web-monetization-extension/issues/329
https://github.com/interledger/web-monetization-extension/issues/331
https://github.com/interledger/web-monetization-extension/issues/332
