### ISSUE TITLE
[TO REFINE] Implement a test page on a website

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#328]
**Purpose**: Build a test page with functionality for creating different conditions or scenarios for testing the WM ext. 

It should have the following **minimum capabilities**, which are needed to test the WM extension:
- [to define]

The page should also have buttons that allow users to:
1. Add a wallet address to the page...and then as part of the testing, we will define the expected impact/behaviour on the WM extension, including:
- the rate of pay should be changed
- if icon is red, it should become green
- if WM is disabled, nothing should happen
2. Remove a wallet address
3. Open a new tab and close it
4. Capture logs of the extension's content & background activities.

**Comment by raducristianpopa** [comment]
Since we are aiming to move Testnet's applications to `try.interledger.tech` (https://github.com/interledger/testnet/issues/1327), should this playground be included in the test network - something like `try.interledger.tech/webmonetization`?

**Comment by tselit** [comment]
Requesting more detailed input from @AlexLakatos on this ticket.

**Comment by tselit** [comment]
@raducristianpopa is able to start working on this, due to existing playground that Radu already uses.

**Comment by raducristianpopa** [comment]
Closed by https://github.com/WICG/webmonetization/pull/466.
