### ISSUE TITLE
[BUG] Extension not stopping me from connecting to a non WM payment pointer 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#331]
### Steps to reproduce

1. Connecting my extension to a wallet 
2. In the wallet address field, I use a payment pointer that is not  WM enabled

<img src="https://github.com/interledger/web-monetization-extension/assets/5781590/dc832eb6-90db-4f54-b9a3-ee4cc25d9ad3" width="300" >

3. I click on the Connect button 
4. my extension is now connected to the wallet 

<img src="https://github.com/interledger/web-monetization-extension/assets/5781590/23a2deb6-6b3d-4cda-b770-d603ffe679c7" width="300" >

### Expected result

The extension should not be able to connect to a non WM pointer. 
Connection should fail with a clear error message explaining the reason to the user 

### Actual result

Extension connects but all payments fail leaving the user confused on why their payments are failing 

### Operating system

Windows

### Browsers

Chrome

### Extension version

Alpha

**Comment by raducristianpopa** [comment]
At the moment, this is only a constraint on the test wallet - "WM Payment Pointer". The extension should work with any wallet address.

**Comment by RabebOthmani** [comment]
@tselit Do you think we should include this in some sort of documentation material as a limitation/constraint as we prepare for beta?

**Comment by tselit** [comment]
To do: this is not an issue (add a comment, discuss with Bibi) and ready to close
