### ISSUE TITLE
[FEATURE REQUEST] Local storage not being cleared after connecting a wallet address

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#334]
### Steps to reproduce

1. Upload public key on the test wallet
2. Fill out the connect wallet form and perform the interaction step
3. Accept the grant on test wallet's IdP
4. Open the extension popup and go to settings page
5. Disconnect the wallet

### Expected result

The connect wallet form inputs should not be prefilled when the wallet address was disconnected.

### Actual result

The inputs are prefilled with the previous data - wallet address, amount and the renew monthly option.

### Operating system

macOS

### Browsers

Chrome

### Browser version

125.0.6422.142

### Extension version

Alpha

**Comment by sidvishnoi** [comment]
> The connect wallet form inputs should not be prefilled when the wallet address was disconnected.

I think it's good that they're prefilled? The fields can still be edited and I can connect same wallet address with a different amount without needing to fill again.

**Comment by tselit** [comment]
To do: add a comment (chat to Radu) and close

**Comment by sidvishnoi** [comment]
@raducristianpopa Ok to close this?
