### ISSUE TITLE
[BUG] invalid text on "send now" button for failed 1-time payment

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#353]
### Steps to reproduce

**Wallet setup**
1. Create a USD sender test wallet account in rafiki.money.
2. Connect the wallet address to WM extension (I have the extension pinned to the browser)

**Visit websites**
1. Visit non-monetized website (google.com) & try to make a 1-time payment. **Result**: payment failed, extension shows error message "This website is not monetized."
2. Open a a WMized website (alexlakatos.com) in a new tab & successfully make a 1-time payment for $1.
3. Change tabs back to a non-monetized website (google.com).

**Try something funky**
4. Use a keyboard shortcut to open the browser dev tools (on Windows, I used `Ctrl+Shift+J`).
5. Move mouse to the dev tools window, and click the Elements tab.
6. Move mouse back to Web browser that still has a non-monetized website open (google.com), then click on the WM ext. to open the extension.
7. Enter an amount to make a 1-time payment to the non-monetized website (this fails with the msg "This website is not monetized").
8. Move the mouse to click back in the Dev Tools window, then search for a term (I used the keyboard shortcut Ctrl+F to search, then typed "monetization" and pressed enter, on the keyboard).
9. Move the mouse back to the WM extension pop-up, which is still open in Web browser with a one-time amount, then click on "Send now".

### Expected result

The 1-time payment to a non-monetized website must fail and the WM extension must display the message "This website is not monetized"

### Actual result

The text on the "Send now" button changes to "Send nowPayment successful"
![image](https://github.com/interledger/web-monetization-extension/assets/90185897/3d6d4dab-1a6d-4fd2-924f-f123d14f6486)

### Screenshots or videos

Watch video from 0 until 1 minute 41seconds: [link to video](https://www.loom.com/share/07ca89dcfd094e89af40e3408be0ab13?sid=8e937c00-0c4a-4c00-8342-82bbfd9c4d7a)

### Additional context
This issue is linked to #292 

### Operating system

Windows

### Operating system version

10

### Browsers

Chrome

### Browser version

Version 126.0.6478.114 (Official Build) (64-bit)

### Extension version

alpha 1 (it says v1.0.1)

**Comment by dianafulga** [comment]
Closed: no longer applicable, because the user cannot see the on time payment UI anymore on non-monetized pages.
