### ISSUE TITLE
[ENHANCEMENT] update tooltip text

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#354]
### Steps to reproduce

1. Install the extension & pin the extension to the browser window.
2. Connect the extension to a wallet.
3. Visit a non-monetized website
4. Hover over the WM extension's icon

### Expected result

When hovering over the WM extension icon, the tooltip displayed should have the following text:
"Web Monetization 
This site is not monetized"

### Actual result

When hovering over the WM extension icon, the tooltip displayed should have the following text:
"Web Monetization 
Has access to this site"

### Screenshots or videos

![image](https://github.com/interledger/web-monetization-extension/assets/90185897/daf0a37e-82d6-4061-8b4b-6f755dff1b61)

### Additional context
On 22 June, we discussed and agreed on the following solution:
- NOTE: for **the Chrome browser only**, the extension cannot suppress text that comes from the browser, SO the Chrome browser appends the following text to the tooltip: "Has access to this site"

So, the extension's tooltip in Chrome will have the following text:
- if a site is monetized: 
        Web Monetization - Active
        Has access to this site.
- if a site is NOT monetized: 
        Web Monetization - Inactive
        Has access to this site.

For all other browser's, the ext tooltip has the following text:
- if a site is monetized: 
        Web Monetization - Active
- if a site is NOT monetized: 
        Web Monetization - Inactive

### Operating system

Windows

### Operating system version

10

### Browsers

Chrome

### Browser version

Version 126.0.6478.114 (Official Build) (64-bit)

### Extension version

alpha build (says v1.0.1)

**Comment by sidvishnoi** [comment]
The "Has access to this site" part is coming from browser. We can perhaps add more details to the title though. Will investigate.

**Comment by tselit** [comment]
> The "Has access to this site" part is coming from browser. We can perhaps add more details to the title though. Will investigate.

Noted, thanks @sidvishnoi .
In that case, as discussed, let us proceed with the following tooltip text:
If a site monetized: Web Monetization - Active
If a site isn't monetized: Web Monetization - Inactive

Also just acknowledging your feedback that the for **the Chrome browser only**, the extension cannot suppress text from the browser, such that the following additional text will be part of the tooltip: 
"Has access to this site"
