### ISSUE TITLE
Improve icons

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#373]
Discussed with @raducristianpopa over https://github.com/interledger/web-monetization-extension/pull/368

Two parts:
- We want a new icon for "user action required" state
- We want the icon's state to be more prominent

For reference, compare the state prominence part with GitHub Notifier extension (the red cross dot in our extension icon maybe visible in screenshot, but not in browser toolbar):
![image](https://github.com/interledger/web-monetization-extension/assets/8426945/27ae897d-3ab7-479d-80d2-63fd7d290a38)

@raducristianpopa tried some icons in Figma, to show more emphasis on state (**new icon**)
<img width="463" alt="image" src="https://github.com/interledger/web-monetization-extension/assets/60383558/73e9bf54-3f18-42fa-9489-bdf98dc2e125">

We want to fix when each icon is displayed as follows:

- WM (continuous payments) is enabled & wallet connected
  - web monetized website (has valid link tag) => active icon + green dot
  - non-web monetized website => active icon + red dot
- WM is disabled and wallet connected
  - web monetized website => inactive + green dot (**new icon**)
  - non-web monetized website => inactive icon + red dot (**new icon**)
- Error state (e.g. out of funds; key error)
  - inactive icon + warning sign (**new icon**)
- Default state
  - Active icon without any dots/signs

Note that just relying on dot's color won't be enough from accessibility perspective. Having some sort of text/icon, such as exclamation mark would be necessary.

**Comment by sidvishnoi** [comment]
Blocked on designs.

**Comment by RabebOthmani** [comment]
Can we take a step back and narrow what we need to communicate out of these icons. I appreciate laying out the different scenarios @sidvishnoi , you're making this super easy for us. I would argue though that some of these states should not be communicated via the icon like errors for example.

**Comment by sidvishnoi** [comment]
There's no other way to communicate errors, as to tell user attention is needed though.

**Comment by tselit** [comment]
@raducristianpopa will share an image of the icon (in context)

**Comment by tselit** [comment]
To do: design conversation with Madalina for error state (thinking exclamation point)

**Comment by tselit** [comment]
Sent request to Madalina today.

**Comment by tselit** [comment]
Received proposed improved icon designs from Madalina on Wed, 18 July:

<figure>
<img src="https://github.com/user-attachments/assets/481ac7a8-cc5d-4ef2-b212-112165cb9e27" width=20%/>
<figcaption>standard icon, WM active, website not monetized</figcaption>
</figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/70900b07-6ee4-4686-a3b2-b7dc15d0e127" width=20%/>
<figcaption>standard icon, WM active, warning & requires user action</figcaption>
</figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/e525d2f1-ee62-40ea-a4d2-967e8f9da993" width=20%/>
<figcaption>standard icon, WM active, website is monetized</figcaption>
</figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/37533f57-35d5-4afb-8b30-d5b6c78e77a6" width=20%/>
<figcaption>inactive continuous payments, website not monetized</figcaption>
</figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/19425221-93f1-434f-a641-fff7ab461410" width=20%/>
<figcaption>inactive continuous payments, warning & requires user action</figcaption>
</figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/67e28d71-25ec-4fb9-bf89-1a9f1f52a55c" width=20%/>
<figcaption>inactive continuous payments, website is monetized</figcaption>
</figure>
<br>
<br>
<br>

Below are 2 possible icon alternatives that we could also consider:
<figure>
<img src="https://github.com/user-attachments/assets/99ba23d9-cf8b-4d34-9193-dfce27e5a8cf" width=20%/>
<figcaption>alternative icon on monetized site</figcaption>
<figure>
<br>

<figure>
<img src="https://github.com/user-attachments/assets/1006955f-4002-41fb-b2d2-4b18420e90f1" width=20%/>
<figcaption>alternative icon with warning & requires action</figcaption>
</figure>

**Comment by RabebOthmani** [comment]
I like these icons!

**Comment by sidvishnoi** [comment]
I'll update PR to use these icons tomorrow. Then we can ship the pre-beta?
