### ISSUE TITLE
[BUG] Not using font that we import from Google fonts

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#374]
Should either use the font (Titillium Web) or remove the stylesheet import.

Discovered here: https://github.com/interledger/web-monetization-extension/issues/332#issuecomment-2191733454

**Comment by tselit** [comment]
@dianafulga  and @sidvishnoi 
The guidance from Madalina and Hui Jing is that: 
https://interledgerfoundation.slack.com/archives/C06CVJRT5N3/p1722412831694959?thread_ts=1722349862.645679&cid=C06CVJRT5N3
- there's no need to import the Titillium Web font as this requires managing additional resources
- let us stick with the font that the extension currently already uses (in Figma, the name of the font is "_Inter_")
- so, we can close this ticket

**Comment by sidvishnoi** [comment]
Oh just in case, Inter is also a custom font. Should update figma to use default system fonts we use.

**Comment by sidvishnoi** [comment]
Need to remove that import though, even if unused.

**Comment by dianafulga** [comment]
I'll remove the fonts and close this ticket
