### ISSUE TITLE
Add UI for "out of funds" error state

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#377]
It would have:
- an error message
- an option to specify amount + recurring flag

**Comment by tselit** [comment]
The UI designs are ready for review by Madalina, before we continue with Development:
[link to "out of funds" designs on Figma](https://www.figma.com/design/0S8Oj8ZB5MvkGtIrVRswDH/Web-monetization?node-id=509-852&m=dev)

**Comment by sidvishnoi** [comment]
From [Slack](https://interledgerfoundation.slack.com/archives/C06CVJRT5N3/p1720092323159379):

> An important question is when to show the out of funds error, is it when they are about to make a payment or if they open the pop up or both - @RabebOthmani 

@sidvishnoi: I think there's two parts here: telling user they're out of funds and second is their action. The error part should be shown only when we can do nothing more without user interaction. We can show the action screen in various scenarios:
- Can do nothing without adding funds (force show this screen)
- One-time pay (should warn user, instead of forcing to add funds)
   - Can make smaller continuous payments, but can't make a larger single payment (not enough funds, but not out of funds)
   - Could make a partial payment (to multiple addresses), just not the total amount user asked for (not enough funds again)
- I think they should be able to manually take action even before running out of funds, that's something we haven't discussed before, so can ignore for now

**Comment by tselit** [comment]
fyi @RabebOthmani and @sidvishnoi 
Yesterday (18 July), Madalina reviewed & was happy with these proposed screens, from the design & identity point of view.
