### ISSUE TITLE
[BUG] Tipping Error "could not facilitate payment for current website" on Web Monetized Sites

### ISSUE THREAD

**Issue by EricaHargreave** [interledger/web-monetization-extension#387]
### Steps to reproduce

**Issue**

Getting a "could not facilitate payment for current website" message when trying to tip Web Monetized Sites with the Web Monetization extension.

**Sites Tested On**

- https://alexlakatos.com/
- https://www.radu.sh/
- https://roamancing.com/ (Web Monetized with the Coil WordPress Plugin) (rafiki test wallet Web Monetization payment pointer)
- https://storytogo.ca/ (Web Monetized with code in the footer) (rafiki test wallet Web Monetization payment pointer)

<img width="1466" alt="Screenshot 2024-07-02 at 11 46 22 AM" src="https://github.com/interledger/web-monetization-extension/assets/101068257/8ef7f026-983e-420f-9061-abf24092864c">
<img width="1508" alt="Screenshot 2024-07-02 at 11 46 55 AM" src="https://github.com/interledger/web-monetization-extension/assets/101068257/b1c6f68d-e849-49d5-9fce-b3db751f6ed6">
<img width="1508" alt="Screenshot 2024-07-02 at 11 37 11 AM" src="https://github.com/interledger/web-monetization-extension/assets/101068257/caa80413-cff1-40c7-8e34-4272369a625a">
<img width="1505" alt="Screenshot 2024-07-02 at 11 36 40 AM" src="https://github.com/interledger/web-monetization-extension/assets/101068257/764c8aad-6a29-488e-a566-54dd242d57ac">

### Expected result

It was expected that each site would receive the tip that they were sent via their payment pointer.

### Actual result

The message "could not facilitate payment for current website" was displayed on the Web Monetization browser extension, and presently, one hour after attempting to tip the accounts, no funds have left the sending wallets or been received by the receiving payment pointers for Roamancing or StoryToGo.

### Operating system

macOS

### Browsers

Chrome

### Extension version

alpha 1 (the ext shows v1.0.1)

**Comment by sidvishnoi** [comment]
I could reproduce this consistently when remaining balance is closer to (or lower than) amount being sent. @EricaHargreave Can you confirm if this is the case above? If not we'd need to investigate more.

**Comment by EricaHargreave** [comment]
I think I just identified the cause of this issue, @sidvishnoi, being that the sender's 'grant' was out of funds, but rather than receiving a message of "insufficient funds, please top up your grant to send this tip", I received a "could not facilitate payment for current website" message, which makes one think there is either an issue with the WM site or the WM extension.

**Comment by sidvishnoi** [comment]
Thanks for confirming @EricaHargreave. We'll be handling this as a part of https://github.com/interledger/web-monetization-extension/issues/144 and https://github.com/interledger/web-monetization-extension/issues/147.

**Comment by EricaHargreave** [comment]
Thanks @sidvishnoi.
