### ISSUE TITLE
[BUG] No warning when sending to real wallet from rafiki.money

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#394]
### Steps to reproduce

1. Go to https://roamancing.com/naturallyours/ (uses fynbos wallet)
2. Setup wallet with rafiki.money
3. No payments can go through

### Expected result

Payments don't go through but there should be an indication in extension, and extension should stop trying to pay.

### Actual result

Extension keeps trying payments indiscrimately.

### Screenshots or videos

![image](https://github.com/interledger/web-monetization-extension/assets/8426945/54841810-125c-433a-ac58-de90d88cdbb8)

![image](https://github.com/interledger/web-monetization-extension/assets/8426945/d7b57138-72ca-4fce-a6b2-c65ce46eab15)

### Operating system

Linux

### Browsers

Chrome, Firefox

### Extension version

alpha2

**Comment by sidvishnoi** [comment]
The bug likely extends to other cases (like not legally allowed to send money to wallet).

**Comment by raducristianpopa** [comment]
I think we need to come up with a threshold. If an X number of outgoing payments are going to fail we should stop/pause the payment session.

**Comment by sidvishnoi** [comment]
Note the `invalid receiver` error in above screenshot, can use that.

**Comment by sidvishnoi** [comment]
Scheduled for discussion this Tuesday, as it can occur with any providers that haven't peered.

We likely want to inform user that can't make payments to all/some payment pointers on this page, and stop trying payments for that payment session.

**Comment by dianafulga** [comment]
**Decision**

Cases: 

1. Continuous payments:

- If all are failing: show the exclamation icon + some warning text (TO DO @RabebOthmani)
- If at least one monetization link is being payed: show the green icon

2. OTP:

- Some links failing: some warning message (TO DO @RabebOthmani)
- All links failing: error message (TO DO @RabebOthmani)

**Comment by RabebOthmani** [comment]
If all links are failing --> error message " We are unable to process the payment. Please check with your wallet provider for more details" cc @dianafulga
