### ISSUE TITLE
Users should have the ability to use the short and a long form for a payment pointer/wallet address

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#411]
### Context

- Users should be able to use the short form (`$`) and the long form (`$`) - ONLY in the extension's UI

### Todos

- Convert `$` to `https:`

**Comment by sidvishnoi** [comment]
In the `<link>` tag?

**Comment by raducristianpopa** [comment]
> In the `<link>` tag? Or just popup?

In the link tag as well.

**Comment by sidvishnoi** [comment]
(Sorry if this was discussed during call)
If this is for backward compat, aren't the existing payment pointers SPSP based?

**Comment by raducristianpopa** [comment]
> (Sorry if this was discussed during call) If this is for backward compat, aren't the existing payment pointers SPSP based?

Updated the issue.
