### ISSUE TITLE
Trigger `load` event after checking the wallet address

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#43]
At the moment, the `load` event is triggered automatically when the WM polyfill is injected which is not the intended behaviour. The `monetization` link should be checked before triggering the `load` event - [spec](https://webmonetization.org/specification/#link-type-monetization).

- Inject polyfill on `document_start` (before `window.onload`) (--- from #78 , implemented here)

**Comment by tselit** [comment]
In progress: @dianafulga will discuss with Radu (25 Jan) before in order to update the estimated effort.

**Comment by dianafulga** [comment]
Missing a clear definition of the "verification of the monetization link". Currently the verification code is spread across multiple files and moments in the user flow like so:
- if valid format for a link (ex: having http/https protocol), time: when opening a new page, location: TabManager
- if link tag in page, time: when opening a new page, location: background
- establish session (which qualifies as verification according to the specs), time: when user clicks on connect (to be changed with the new flow), location: background
- if WM is disabled in the extension (not yet implemented - TBD in the new flow), time: to be decided, location: to be decided

According to the specs, if the verification fails, we should emit an error event, but currently is not implemented at every step during all the steps mentioned above, to be decided if and where we want to implement it

**Comment by dianafulga** [comment]
Closing the ticket as the load event has been moved to be triggered after a session has been established.
