### ISSUE TITLE
[BUG] Having a new window opened makes the extension display "This site is not web monetized" all the time, even if on monetized website

### ISSUE THREAD

**Issue by dianafulga** [interledger/web-monetization-extension#438]
Go to a monetized website. The exension displays the right UI.
Open google drive in another window.
Go back to the monetized website. The extension displays the wrong UI.
Close the google drive link.
Go back to the monetized website. The extension displays the right UI.

https://github.com/user-attachments/assets/1ab1d04d-c5f6-439a-b9b4-06639634d004

**Comment by sidvishnoi** [comment]
This looks like a race condition, on us passing the `IS_TAB_MONETIZED` event. https://github.com/interledger/web-monetization-extension/issues/381 would help.

**Comment by sidvishnoi** [comment]
@dianafulga causes issues only with google drive or any other site too?

**Comment by sidvishnoi** [comment]
@dianafulga Let me know if it's reproducible with https://github.com/interledger/web-monetization-extension/pull/420 (to avoid us doing the same work in different manner)
