### ISSUE TITLE
Design system & UI

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#44]
### Context

Implement extension Popup UI

### Todos

Setup
- [x] #48

Components
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54

Layout
- [x] #55

Routing
- [x] #56

**Comment by tselit** [comment]
Adding a reference to the initial UI design:
<img width="674" alt="image" src="https://github.com/interledger/web-monetization-extension/assets/90185897/4bda3bd8-4e34-4cb7-ab5a-8ed745cd5267">
