### ISSUE TITLE
Settings page - Connect wallet

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#46]
### Context

Implement settings (setup) page.

### Todos

- For a user that does not have a connected wallet address, the settings page should be displayed
- Add setup form:
  - wallet address
  - amount
  - amount type (recurring/single use)
- Validate form fields on submission
- For a user that has a connected wallet address, all the setup forms fields should be disabled and read-only. The only action that the user can perform: disconnecting the wallet address

**Comment by tselit** [comment]
**Memo to selves**: team to discuss with Alex about amending the current v1.0 design to have the public key displayed immediately upon landing on the Settings page, right where the wallet address appears.
