### ISSUE TITLE
Extension starts payments even before page load

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#477]
In Chrome, **during prerendering**, the extension starts checking/creating payments while we're typing URL in address bar. We should start the sessions/fetching only after page load, not during prerender.

If we change the URL after typing (before hitting enter), the payments continue as if tab was never closed.

**Comment by raducristianpopa** [comment]
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/1ikOwxWiU_g
