### ISSUE TITLE
[BUG] Fynbos wallet invalid client error

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#489]
### Steps to reproduce

1. Testing with a ZAR Fynbos wallet
2. Removed all WM extension keys from the Fynbos wallet
3. Open the WM extension
4. Enter the fynbos wallet address and an amount greater than zero
5. Leave "renew amount monthly" disabled
6. Click Connect 

### Expected result

Display error message: 
`Failed to connect. Please make sure you have added the public key to the correct wallet address.`

### Actual result

Displays error message: `invalid client`
![image](https://github.com/user-attachments/assets/d5b33225-bcdb-408a-9da4-2e9cc1740ca1)

### Screenshots or videos

From the build shared on the channel 6 Aug: 
https://www.loom.com/share/0b5b34fdf5104a79a1d4ded00eafe152?sid=de33a394-8138-4e0e-a05a-b00e3f960b1f

### Additional context

The same scenario using a USD rafiki.money **test payment pointer** worked as expected, and the correct error message was displayed: 
`Failed to connect. Please make sure you have added the public key to the correct wallet address.`

![image](https://github.com/user-attachments/assets/bee4b5b2-77eb-43bd-8d6f-2cdc63546ca3)

### Operating system

Windows

### Operating system version

10

### Browsers

Chrome

### Browser version

Version 127.0.6533.89 (Official Build) (64-bit)

### Extension version

the build shared on 6 August on Slack https://interledgerfoundation.slack.com/archives/C06CVJRT5N3/p1722933667156999?thread_ts=1722853980.760009&channel=C06CVJRT5N3&message_ts=1722933667.156999

**Comment by sidvishnoi** [comment]
Looks like Fynbos hasn't updated to Rafiki v1.0.0-alpha.14 yet, which [includes that error handling](https://github.com/interledger/rafiki/releases/tag/v1.0.0-alpha.14#:~:text=chore(auth)%3A%20return%20objects%20during%20GNAP%20errors). Will check with them. If no soon-ish plans, we will have to match both error code and description in extension.

**Comment by sidvishnoi** [comment]
Fynbos is looking into updating Rafiki tomorrow, so might not need to do this on our end.

**Comment by sidvishnoi** [comment]
@tselit Fynbos updated today and this issue is now resolved. Please test the extension more with Fynbos wallet to check if there are any other issues.
