### ISSUE TITLE
Add input component

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#50]
### Context

- #44

### Todos

- Implement a reusable input component (text)
- For the amount input, we can use `react-number-format`
- The component should have handling for focus, disabled and other required states

> [!NOTE]  
> We can have two separate input components (text and amount).
> A separate label component can be added, which can be used for other form items as well.

**Comment by tselit** [comment]
Considered whether there are error states that need to be handled or not. For now, none are defined, so the assumption is that there are none.
