### ISSUE TITLE
Add switch component

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#51]
### Context

- #44

### Todos

- Implement a reusable switch component
- The switch should have two size variants:
  - `default` (used in the popup header to disable WM globally)
  - `sm` (used in the main page to disable continuous payments stream for a certain site)
- The component should have handling for focus, disabled and other required states
- Consider following the [WAI ARIA Switch pattern](https://www.w3.org/WAI/ARIA/apg/patterns/switch/) for a11y guidelines

> [!NOTE]
> For handling different variants [CVA](https://cva.style/docs) can be used.

**Comment by tselit** [comment]
Currently busy with unit tests. Anticipating readiness for review within the next day.

**Comment by tselit** [comment]
Review is in progress, already received feedback from Radu.
