### ISSUE TITLE
Add radio group component

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#52]
### Context

- #44 

### Todos

- Implement a reusable radio group component
- The component should have handling for focus, disabled and other required states
- Consider following the [WAI ARIA Radio Group pattern](https://www.w3.org/WAI/ARIA/apg/patterns/radio/) for a11y guidelines

**Comment by tselit** [comment]
PR should be ready for final review by EOD, 16 Jan 2024

**Comment by tselit** [comment]
Addressed review comments & awaiting final review.
