### ISSUE TITLE
[UX Improvement] Setup page 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#565]
### Context

**_This is based on testers feedback_**
It can be confusing to understand the steps to take to configure the extension , that is to successfully connect it to a wallet and setup a budget to use. There's room to make the experience on this page better and easier for the users.
For example: public key might be confusing for non technical users / the connect button is always enabled

### Todos

- Connect button should be disabled until all steps are taken. This is a visual cue for the user that something needs to be done.
- Review and update copy to be clearer
- Show “Amount is required” message when no amount is entered (amount is $0.00)
- Show “Wallet address is required” message when wallet address is left empty
- Update grey out colour to indicate that a field needs filling (https://github.com/interledger/web-monetization-extension/issues/559)

### Acceptance Criteria 

1. The extension should connect to a wallet if all of the following criteria are met at the same time:

- The user has typed a valid wallet address 
- The user has specified a valid amount to allocate as a budget 
- It is not possible to verify from within the extension whether the user copied the public key into the wallet. This verification step will be done at later stages. 

Until all criteria is met, the 'Connect' button should be disabled.

2. The extension should have input validation

- If the user types an invalid wallet address, show ' **The Wallet address is invalid**' message.
- The user has to enter an amount greater than $0.00.
- If the user types an invalid amount, show '**An amount greater than $0.00 is required**' message.

3. Input fields contain a placeholder with grey-colored text 
4. The wallet address field has a header above it with the text '**Enter your wallet address**' 
5. The amount field has a header above it with the text ' **Enter the amount to allocate from your wallet**'
6. The public key field has a header above it with the text ' **Copy this key and paste it into your wallet**'
7. The renew amount toggle should be horizontally centred with the amount field to its right.
8. The renew toggle has a text ' **Renew monthly**' 
9. The setup page has a header with the text ' **Let's get you set up!**! 
10. The setup page has a subheader with the text ' **Just a few quick steps to connect the extension to your wallet**' 

<img src="https://github.com/user-attachments/assets/81c6d8c6-2709-4f61-9eab-8dcfae5d8057" width="300">

**Comment by melissahenderson** [comment]
Suggestions:
- 2.a **Your wallet address or payment pointer is invalid. Check that you've entered it correctly.** (I don't know if we still have to refer to payment pointers nor do I know if we have enough room for a longer message)
- 2.b Messaging is fine, just curious if the dollar sign is hardcoded or if it will change based on user's currency
- 4 **Enter your wallet address or payment pointer.**
- 9 My personal preference is sentence case (**Let's get you set up!**)

**Comment by sidvishnoi** [comment]
Sign will change with currency

**Comment by RabebOthmani** [comment]
@melissahenderson Thank you! For the payment pointer, as a team and based on the feedback we received, the consensus is that it may be confusing for a user who's not WM savvy. We want to use simple terms easy to understand by everyone and anyone. @sidvishnoi @tselit @raducristianpopa your thoughts?

**Comment by melissahenderson** [comment]
@RabebOthmani I agree with your statement 100%. Just thinking back to what A said during the work week. I'm happy with it not referencing both.

**Comment by tselit** [comment]
Hey @RabebOthmani  and @melissahenderson 
IIRC payment pointer made a come-back on the UI because one of the wallets only uses the term payment pointer...and so the challenge was how to make it clear to users of those wallets that this field is also for their payment pointer.

**Comment by raducristianpopa** [comment]
This was discussed during the work week as well and we decided to add the payment pointer term as well. The wallet providers can decide what term they want to use and we cannot enforce this for them (what @tselit mentioned). By specifying both terms, it will mean that we support both the long and the short form (`https://wallet.com/john` and `$wallet.com/john`). For now, I would keep the thing as is - using both terms and we can revisit this if the users are confused.

**Comment by RabebOthmani** [comment]
To keep track on changes based on feedback and conversations, I'll make amendments in the comments section. 
Text to update : 
* Enter wallet address/ payment pointer.
* Enter amount to allocate from wallet. 
cc @sidvishnoi
