### ISSUE TITLE
[FEATURE REQUEST] Improve payment confirmation 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#567]
### Describe the feature you would like to request

**_This request is based on tester's feedback_** 

After sending a payment, the confirmation within the button happens quickly and then resets. There's a risk of the user not noticing the confirmation if they got slightly distracted away from that screen. 

### Describe the solution you would like

Stay in confirmed state until user takes an action (maybe an ok or return button ) 

### Acceptance criteria

- The extension should show an error message if not able to facilitate the payment with the text ' **Something went wrong. Please try again'**
- The extension should show a confirmation message if able to facilitate the payment with the text **' Thanks for your support.'**
- Once a payment is facilitated, the amount is reset to 0 and the 'pay now' button is disabled. 
- The text above the amount should say **' Support [ website url]'**
- the 'pay now' button is enabled once the amount is > 0. 
~~- The extension should say 'donate now' instead of 'pay now'~~ 

**_Screenshot is for prototyping purposes only and not a final design_**
<img src="https://github.com/user-attachments/assets/121b978b-1c96-48a9-a8cb-5e2984949784" width="300">

**Comment by melissahenderson** [comment]
Suggestion: instead of "Thank you for supporting . You can now make more donations."
How about: "Thanks for your support." It sounds natural and stays away from the other terms we're chatting about in Slack.
Then the action button can be "Close"

As far as "Pay Now" and etc, it looks like those conversations are still in progress.

**Comment by RabebOthmani** [comment]
@sidvishnoi @raducristianpopa the design for the payment page and different OTP states is available on Figma.
