### ISSUE TITLE
[BUG] Extension does not work in Chrome (ver 128, 64-bit,Ubuntu)

### ISSUE THREAD

**Issue by lengyel-arpad85** [interledger/web-monetization-extension#572]
### Steps to reproduce

1. add a monetization link to a website
2. open website in Chrome (ver 128, 64bit, Ubuntu)
3. have WM extesnion installed (either from store or manually)
4. open WM extension, observe extension displaying "Website is not monetized"

### Expected result

Extension should display normal controls and info, since website has a valid monetization link. 
All this works on Mac, Chrome, but not on Ubuntu, Chrome

### Actual result

![Screenshot from 2024-09-05 16-16-24](https://github.com/user-attachments/assets/361ce399-23f4-4488-a05e-706f46c3438b)

displayed error persists even after refreshing the page.

as a sanity check I tried relList.supports monetization and even that is giving a false value

![Screenshot from 2024-09-05 16-18-51](https://github.com/user-attachments/assets/5de12709-84fd-4c36-b6c9-342e9c11ea40)

### Operating system

Linux

### Operating system version

Ubuntu 23.04

### Browsers

Chrome

### Browser version

Version 128.0.6613.119 (Official Build) (64-bit)

### Extension version

0.1.1

**Comment by Har33m-Sha1kh** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by sidvishnoi** [comment]
Web monetization is aimed to work only on secure contexts (https URLs), as per spec.

I think it would be better to disable the popup/extension (IIRC, browser would show default "cannot access this site" message) or show a different custom message (but might cause additional confusion?) on non-https pages. cc @RabebOthmani

**Comment by RabebOthmani** [comment]
If a website is monetized, we should never show the 'website not monetized' message as it's fundamentally wrong. We can and should a more explicit clear message on why it's not possible to use the WM extension in this instance.

**Comment by tselit** [comment]
Will be addressed in #584

**Comment by lengyel-arpad85** [comment]
@tselit that's ok, thank you for the clarification
just have in mind that in my tests it did work on Mac / Chrome on **http** and other browsers, the only exception was the LInux / Chrome why I reported it for this combo :)

**Comment by lengyel-arpad85** [comment]
> @tselit that's ok, thank you for the clarification just have in mind that in my tests it did work on Mac / Chrome on **http** and other browsers, the only exception was the LInux / Chrome why I reported it for this combo :)

update: where it worked with **http** I was using a dev build, so you can ignore my previous concern

**Comment by tselit** [comment]
Cool, and thanks for closing the loop on this @lengyel-arpad85.
Closed ✔️
