### ISSUE TITLE
[UX Improvement] Add ? question mark icon for users to learn more

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#573]
### Describe the feature you would like to request

**This request is based on closed beta testing feedback:** 

On the extension's landing page, before a user connects their wallet, allow the user to learn more about: 
- what a "Wallet address or payment pointer" is, and
- what a "Public key" is (that's **if** we keep the term "public key")

### Describe the solution you would like

On the extension's landing page, before a user connects their wallet, add a "learn more" hyperlink or the question mark icon to the right side of the:
- "Public key" text OR the text "Copy the public key below and paste it into your wallet" 
- "Wallet address or payment pointer" text 
 
such that when a user clicks on the icon or hyperlink, they get redirected to documentation, launched in a separate tab, to learn more about a public key, [wallet addresses](https://webmonetization.org/docs/resources/glossary/#wallet-address) or [payment pointers](https://webmonetization.org/docs/resources/glossary/#payment-pointer).

### Additional context

Suggesting the locations highlighted in the attached image.
<img src="https://github.com/user-attachments/assets/2614b7e6-5822-4253-8284-2d3f468fdd87" width=40% />

**Comment by RabebOthmani** [comment]
Isn't this going to get sorted by adding the post-install how to page?

**Comment by tselit** [comment]
> Isn't this going to get sorted by adding the post-install how to page?

Okay cool, I'm happy to park this one 👍🏾

**Comment by sidvishnoi** [comment]
This one can be closed, right?

**Comment by tselit** [comment]
Agreed to cancel this issue on 11 Sept 2024.
