### ISSUE TITLE
Configure extension storage

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#58]
### Context

- #45

### Todos

  - WM enabled flag (global)
  - List of websites where WM was disabled by the user
  - Wallet address information (id, authentication server, resource server, asset code, asset scale)
  - Remaining balance (can be stored alongside wallet address information?)
  - Amount type (recurring or single-use)
    - can be a flag (`recurring: true | false`)
  - Access tokens & manage URLs for:
    - quotes
    - outgoing payments
  - Rate of pay (cents per hour)

Info: related to task #59

**Comment by tselit** [comment]
@ionutanin update on 23 Jan: 
**Complete** dev for state management store config & local context provider with custom hooks to retrieve data from store.
**In progress**: unit testing
**Goal**: have ready for review by the end of the 25 Jan

**Comment by tselit** [comment]
@ionutanin has now added unit tests (with min. 80% coverage), and is about to begin the next #59 .

**Comment by tselit** [comment]
Agreed that @ionutanin will address review and get final review in order to merge PR today (16 Feb).
