### ISSUE TITLE
Configure popup store

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#59]
### Context

- #45

### Todos

- Information stored in the extension storage should be sent to the popup
- Setup a context provider that registers of all the information that was sent from the extension
- The amount that needs to be sent per second (derived from the rate of pay value that is received from the extension storage)

Info: related to task #58

**Comment by tselit** [comment]
Discussed with @ionutanin and aiming to have this completed and ready for code review by EOD tomorrow (17 Jan)
