### ISSUE TITLE
[BUG] Misleading successful payment msg even when wallet payment fails

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#592]
### Steps to reproduce

**Tester feedback**
Used `rafiki.money` to setup 2 different wallets, to easily track my WM sending wallet (starting balance of $50) and receiving wallet (starting balance of $0). 
Both wallets are in USD, they're configured to have WM-enabled payment pointers.

- connect WM extension to the sending wallet.
- setup the WM playground to receive payments into 2 payment pointers on the receiving wallet
- use the WM extension to make continuous payments to the WM playground
- use the WM extension to make a one-time payment of $2.50, which split the amount in half, to send to each of the 2 receiving pay-pointers

**Observation**: The extension shows a "Payment successful" message
**Results**: Waited 5 minutes...30 minutes...about 20 hrs but there were no successful, or even rejected transactions, and the balances remained unchanged, for each wallet.

### Expected result

None of the payments from the WM extension actually succeeded, and so the extension should **not** show a message indicating successful payment.

### Actual result

When making a one-time payment, the extension showed a "Payment successful" message even though the transaction didn't actually succeed.

### Additional context

I was concerned that maybe the WM playground or extension may be doing something unexpected.
When I repeat the scenario using a Fynbos wallet, the payments go through.
Erica didn't use the WM playground, instead she added the receiving payment pointers onto a website, but unfortunately she made similar observations.

### Operating system

Windows

### Operating system version

10

### Browsers

Chrome

### Browser version

Version 128.0.6613.115 (Official Build) (64-bit)

### Extension version

private beta release

**Comment by sidvishnoi** [comment]
@tselit Can you share the wallet address of:
- connected wallet
- and the website?

**Comment by tselit** [comment]
Sure @sidvishnoi . The website was the WM playground, and the connected wallet was: 
$ilp.rafiki.money/3rd-new-wm  
(this was created specifically for WM, with the "I want to use this payment pointer for Web Monetization" checkbox ticked)

**Comment by sidvishnoi** [comment]
So me and Radu couldn't both reproduce with non-WM payment pointers.
Also note, WM payment pointers are going away soon. The regular ones will work for WM.
