### ISSUE TITLE
Rate of pay slider

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#60]
### Context

- #47

### Todos

- Add rate of pay slider
- The slider should have these hourly rates:
  - default: 0.60 (i.e. sixty cents per hour)
  - step: 0.01
  - min: 0.00
  - max: 1.20 (not sure about this value at the moment, but it can be easily changed) 
- Whenever the user changes the slider value, update the rate of pay in the extension storage and recalculate the amount that needs to be sent every second (which will be stored in the extension state)
- Display the current rate of pay and the remaining balance
- Add switch component to disable WM for the current website

> [!NOTE]  
> If the slider is dragged to its minimum value (0.00), we can disable the WM for the current website.

Linked to #53

**Comment by ionutanin** [comment]
This will be in ready for review by tomorrow

**Comment by tselit** [comment]
Currently adding unit test cases, aiming to put into review on Mon, 19 Feb.

**Comment by tselit** [comment]
PR review feedback received & will work on the feedback.
Aiming to merge this by end of this week.
