### ISSUE TITLE
Handle globally en/disabled WM

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#61]
### Context

- #47
- Users have the option to en/disable WM globally (which applies for every website)

### Dependency
This is dependent on ticket #58 

### Todos

- Disabled: display an informational message in the main page, that notifies the user about WM being turned off
- Enabled: inject polyfill if enabled

**Comment by tselit** [comment]
**Current status**: this is ready for review, but would like to wait for #60 to be merged so that this can be re-tested on the latest (merged) branch. There may be small changes needed after re-testing, but should be manageable.
