### ISSUE TITLE
[Setup]: Automate key addition for GateHub

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#618]
Part of https://github.com/interledger/web-monetization-extension/issues/613

**Comment by sidvishnoi** [comment]
I've done most of the required reverse engineering 😄 
We can do most the work with API requests, without needing much DOM clicking stuff.

But implementation blocked by https://github.com/interledger/web-monetization-extension/issues/632

**Comment by RabebOthmani** [comment]
What's the blocker on this one @sidvishnoi @DarianM

**Comment by sidvishnoi** [comment]
@RabebOthmani https://github.com/interledger/web-monetization-extension/issues/632 as before.

**Comment by sidvishnoi** [comment]
https://github.com/interledger/web-monetization-extension/issues/632 is not exactly fixed, but some improvements let us move forward on key addition.
