### ISSUE TITLE
Ability to disable WM 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#623]
### Context

Now that we are moving the rate of pay and continuous payment control into a global setting, we need a way to allow users to disable WM if they choose to. 

Related to https://github.com/interledger/web-monetization-extension/issues/568

### Todos

* Design the best way to disable WM 
* Implement design 

### Acceptance Criteria 

- An Enable/Disable toggle will be available in the top right corner next to the Settings button.
- When WM is disabled, the following text will show on the screen : **'It looks like Web Monetization is disabled. To enable it, please adjust the toggle (icon) at the top right of the popup.'**

![WM enable-disable](https://github.com/user-attachments/assets/392dbf53-5329-4e8a-b6df-cb9144cb7ef8)

**Comment by melissahenderson** [comment]
I have a suggestion for a shorter string: 

> It looks like you've disabled Web Monetization. To enable it, click the toggle in the upper right.

A few thoughts, for what they're worth...

- "It looks like Web Monetization is disabled." Is it possible that this message is misunderstood as meaning the site isn't web monetized? I guess anything and everything is possible ;)
- I know saying "please" is polite, but I don't think it's necessary here. Just my opinion.
- I think most people know what a toggle is. I feel strongly that "(icon)" isn't necessary.
- Semantics here, but top-right is where the settings cog is. Either way, if most people know what a toggle is, they won't be confused :)
- I don't think we should use the term "popup". To see the message, the user is already where they need to be. Other than top right or upper right, I don't think we need to clarify where they are in the UI.
