### ISSUE TITLE
[Setup]: Add consent screen before starting key-add automation

### ISSUE THREAD

**Issue by sidvishnoi** [interledger/web-monetization-extension#625]
Part of https://github.com/interledger/web-monetization-extension/issues/613

**Comment by RabebOthmani** [comment]
![consent screen](https://github.com/user-attachments/assets/b3bf549a-f9d0-4a26-8117-bd6c968caf9b)

For the consent screen: 

- Background: same as the playground or Rafiki for the sake of consistency

- Consent button - users will be directed to the wallet . **Label: Agree**
- Cancel button - **Label: Decline** . Open extension with key to add manually. If opening the pop up is not possible, show a message on the screen that says **' You have chosen not to provide consent. To connect to your wallet, please open the extension and follow the instructions provided manually.'** 

- Consent message: **By agreeing, you consent to us automatically accessing your wallet to securely add a key. Please note, this process does not involve accessing or handling your funds.**
