### ISSUE TITLE
WM ext browser support - Edge

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#67]
### Context

WM extension compatibility with the Microsoft Edge browser.

### Todos

TBC

**Comment by tselit** [comment]
Bibi to do: test on Edge and then should be ready to close

**Comment by sidvishnoi** [comment]
To test: How it works in split-window mode (https://github.com/interledger/web-monetization-extension/pull/366#discussion_r1673836423)

**Comment by raducristianpopa** [comment]
In split view, the extension is only taking into the consideration only the first pane from the split view when updating icon. If we are on a non-monetized website in the first pane and on a web monetized one in the second one, the icon will have the non-monetized website identifier.

<img width="990" alt="image" src="https://github.com/user-attachments/assets/11b573db-4a92-4ca2-88df-085f3bef780f">

**Comment by raducristianpopa** [comment]
Arc's split view should be checked as well.

**Comment by RabebOthmani** [comment]
Blocked as we wait for the MS support team

**Comment by sidvishnoi** [comment]
https://github.com/microsoft/MicrosoftEdge-Extensions/discussions/102 🤷🏽‍♂️🤦🏽

**Comment by sidvishnoi** [comment]
Found the sender port in Runtime.Port message handler returns correct tab 🎉 
```
port.onMessage.addListener((message, sendingPort) => {
   console.log(sendingPort.sender?.tab?.id);
});
```

So, we can make a short connection on content script inject and store tabId for use in future messages?

**Comment by sidvishnoi** [comment]
Everything works once we get right tabId, except Edge doesn't update the icon (even with correct tabId!)
