### ISSUE TITLE
[UI improvement] Centre the "To adjust your budget" text on landing page

### ISSUE THREAD

**Issue by tselit** [interledger/web-monetization-extension#722]
### Describe the feature you would like to request

Currently, the extension's landing page shows the following text right-aligned: 
To adjust your budget or rate of pay, click on :gear:

This is a minor UI improvement request to centre the text.

### Describe the solution you would like

On the extension's landing page, use centred alignment for the following text, with its gear icon: To adjust your budget or rate of pay, click on :gear:

<img src="https://github.com/user-attachments/assets/f0c3c9b1-ea9c-4001-b60f-006045f064da" width=40%>

### Additional context

Here is the design in Figma:
https://www.figma.com/design/0S8Oj8ZB5MvkGtIrVRswDH/Web-Monetization?node-id=872-502&t=oYNtzfTANF8253cL-4

**Comment by arashveysi3** [comment]
working on it. leave it to me plzz

**Comment by arashveysi3** [comment]
having serious problems with creating a test wallet. I can't get verified...

**Comment by sidvishnoi** [comment]
Hi @arashveysi3, do you mean you are facing difficulties getting verified at https://wallet.interledger-test.dev/? If so, can you trying refreshing page? If that fails, please clear cookies and storage (or open in new private window) and try signing up/logging in again.

**Comment by sidvishnoi** [comment]
FWIW, I'm writing a developer's guide for the extension, and will also include test wallet information there. It should be available by tomorrow.

**Comment by arashveysi3** [comment]
Hey @sidvishnoi Thanks for getting back to me
Yes I did that too. but still can't get verified at https://wallet.interledger-test.dev/
if so, I will wait till tomorrow for test wallet information or you can share the info with me today :)

**Comment by sidvishnoi** [comment]
@arashveysi3 Does it keep sending you to KYC page over and over even after completion? Please do try logging in a separate private window (sometimes there's stray cookies in test wallet).

**Comment by arashveysi3** [comment]
> @arashveysi3 Does it keep sending you to KYC page over and over even after completion? Please do try logging in a separate private window (sometimes there's stray cookies in test wallet).

After completion of registration when I get back it says I have to resubmit my docs. 
Used my phone and another device but still same thing happens

**Comment by Tymmmy** [comment]
@arashveysi3 what is the email you used for signup?

**Comment by arashveysi3** [comment]
I checked again and it's fixed now!
Okey back to my task :)

**Comment by arashveysi3** [comment]
@sidvishnoi another question,
how can I get to the page which you needed to be fixed?

the only page I have is: 

![Screenshot (11)](https://github.com/user-attachments/assets/6bb488c1-0e08-4237-af16-a3680e0572b5)
 
anddd of course I tried interledger Boutique, still it says `this website is not monetized`

**Comment by sidvishnoi** [comment]
@arashveysi3 You need to be on a monetized website to see the other screen. You can visit this [simple WM test on my website](https://sidvishnoi.com/test/wm/), or try more customizable behavior by adding wallet address to [Web Monetization Playground](https://webmonetization.org/play/).

**Comment by sidvishnoi** [comment]
You'd need to update `src/popup/pages/Home.tsx`

**Comment by arashveysi3** [comment]
Got it! fixed please review and let me know if any improvements needed.
hope it helps!

**Comment by sidvishnoi** [comment]
@arashveysi3 don't forget to send PR 😄

**Comment by arashveysi3** [comment]
> @arashveysi3 don't forget to send PR 😄 

Sorry
Thought I did before and we are on PR page conversation. 😂😂
