### ISSUE TITLE
Add extension storage wrapper

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#76]
### Context

Create a storage wrapper that has the ability to return values (single or multiple) in a type-safe manner.

### Todos

_TBD_

**Related tickets**: #92 (please see PR review comments for the #93 ). The intention is to (possibly) move some of the code that to this wrapper, which was originally submitted in the PR.

**Comment by tselit** [comment]
To update context after call @raducristianpopa - 15 Feb
