### ISSUE TITLE
Allow checking for WM support before window's load event

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#78]
### Context

With the current extension, checking for WM support is possible only after `window`'s load event. The page should be able to check for WM support before `window`'s load event is triggered.

- WM Spec: [Checking if Web Monetization is supported ](https://webmonetization.org/specification/#checking-if-web-monetization-is-supported)

### Todos
- Inject polyfill on `document_start` (before `window.onload`) (--- ADDRESSED IN #43 )
- Details for MV2 and MV3: #9 (--- ADDRESSED IN #163)

**Comment by tselit** [comment]
Addressed in https://github.com/interledger/web-monetization-extension/pull/203.
Ready to close.
