### ISSUE TITLE
Display WM icon differently if website is/isn't monetized

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/web-monetization-extension#79]
### Context
When a user has the WM extension installed, **and** they have successfully connected their wallet address to the extension, then the icon of the extension must look different depending on whether the user is currently visiting a web monetized website or not.

When a user is visiting a site:
- If the site has no monetization tag with a valid wallet address url:
<img src="https://github.com/interledger/web-monetization-extension/assets/90185897/54bbb22b-c2e9-48d4-99af-ea2047869872"  width="5%" height="5%">

- If the site has at least one monetization tag with a valid wallet address url:
<img src="https://github.com/interledger/web-monetization-extension/assets/90185897/42404ce5-85f9-4f0f-a56c-776f9aa8f728">

- If extension has web monetization globally disabled:
<img src="https://github.com/interledger/web-monetization-extension/assets/90185897/514f0d21-f966-47ee-aa8f-3876edd09909"  width="6%" height="6%">

**Comment by ionutanin** [comment]
as @raducristianpopa suggested:
we should update the background message handler to use switch case rather than use separate files for each message

**Comment by tselit** [comment]
We decided to repurpose this ticket, so please disregard any of the comments prior to 10 Apr 2024

**Comment by tselit** [comment]
Should be ready for peer review on Wed, 17 Apr. Aiming to merge by the end of this week, 19 Apr.

**Comment by tselit** [comment]
Review feedback from Max: 
- when WM is globally disabled
- then navigate to a WMized website
- then enable WM globally
- expected behaviour: the WM icon should be updated to show that the site is monetized but currently the WM ext icon appears as though the site is NOT WMized

**Comment by tselit** [comment]
Secondary issue found: 
- the state the that the icon was in on the previously opened tab remains (or is carried over) when a new (blank) tab is opened (this can be confusing as it may appear as WM active or disabled, or whatever the previously opened site's WM status was).
- still under discussion

**Comment by tselit** [comment]
Identified another possible issue when the global enable/disable toggle is switched:
- When the extension is connected to a wallet, and WM is globally enabled.
- The user visits a WMized website, so the extension begins paying the website (i.e. the WM icon should have a green tick).
- If the user disabled WM globally, still remaining on the website, then the WM icon should have a little red cross (which is currently the case, so good :white_check_mark:).
- _Issue_: while remaining on the same monetized website, the user enables WM again globally. The WM ext icon currently remains in its previous state (i.e. disabled), but it should actually be updated to be active with a green tick.

**Comment by tselit** [comment]
**Related to Issue 1 above**: the WM is not triggered when re-enabling WM globally. This will be addressed as part of this ticket.
